blueprint:
  name: Zooz Scene - Cover Switch
  description: Easily setup Zooz scene controller with a cover.
  domain: automation
  input:
    scene_source:
      name: Scene Controller
      selector:
        device:
          multiple: true
          filter:
            - model: ZEN32
    open_key:
      name: Open Button (scene key)
      description: property_key for OPEN (e.g., "001" or "002")
      default: "001"
      selector:
        select:
          options: ["001", "002"]

    close_key:
      name: Close Button (scene key)
      description: property_key for CLOSE (e.g., "003" or "004")
      default: "003"
      selector:
        select:
          options: ["003", "004"]
    cover:
      name: Cover
      selector:
        target:
          entity:
            domain: cover

mode: single

triggers:
  - device_id: !input scene_source
    id: open
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: !input open_key
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene !input open_key
    trigger: device
    # Key Pressed
    value: 0

  - device_id: !input scene_source
    id: close
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: !input close_key
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene !input close_key
    trigger: device
    # Key Pressed
    value: 0

  - device_id: !input scene_source
    id: stop
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: !input open_key
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene !input open_key
    trigger: device
    # Key Pressed 2x
    value: 3

  - device_id: !input scene_source
    id: stop
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: !input close_key
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene !input close_key
    trigger: device
    # Key Pressed 2x
    value: 3

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: open
        sequence:
          - action: cover.open_cover
            target: !input cover

      - conditions:
          - condition: trigger
            id: close
        sequence:
          - action: cover.close_cover
            target: !input cover

      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - action: cover.stop_cover
            target: !input cover
